export const SCHEMA_VERSION = "2.0.0";
export const SCHEMA_VERIFIED_AT = "2026-09-11T15:04:43Z";

const field = (
  type: string,
  nullable: boolean,
  meaning: string,
  options: Record<string, unknown> = {},
) => ({ type, nullable, meaning, ...options });

export const GLOBAL_GUIDANCE = {
  tenancy: "Every request is scoped server-side to the organization assigned to the authenticated agent key. organization_id is not a caller-selectable filter.",
  freshness: "as_of is the API request time, not the Ninox-to-Supabase sync time. These tables have no source-updated timestamp, so source freshness cannot be proven from the row itself.",
  answer_evidence: [
    "State the report/table, normalized filters, exact period, result, page_count or total_count, as_of, and material caveats.",
    "Do not treat page_count as a total. Use total_count and follow next_offset while has_more is true when all rows are required.",
    "A successful 200 response with an empty page means no rows matched when total_count is 0. An offset beyond the final result is rejected with HTTP 416. Neither case proves the upstream Ninox source is current.",
  ],
  unsupported_or_external_questions: [
    "Planned/scheduled departures require the live Ninox Schedule_Teams source; that table is not available through this function.",
    "The exact Ninox in-yard/off-duty and on-road metrics require days_in_yard_ and numeric insurance-choice logic. Those fields are not present in public.trucks, so this function cannot reproduce those metrics accurately.",
  ],
  join_rules: [
    "DriverPay.DriversDB_ID is text while drivers.Ninox_ID is numeric. In SQL use DriverPay.DriversDB_ID = drivers.Ninox_ID::text; the API returns both as JSON values.",
    "Historical truck keys in DriverPay, returns, and settlements are text while trucks.truck_number is numeric. Normalize to the same representation before comparing.",
    "Use a LEFT JOIN from historical tables to the current trucks master. Historical truck numbers can be absent from the current master; an inner join silently drops valid history.",
    "returns.Ninox_ID identifies the Returns source record and is not a driver ID. Do not join it to drivers.Ninox_ID.",
  ],
};

export const TABLES = {
  driver_pay: {
    report: "driver_pay",
    source: 'public."DriverPay"',
    ninox_source: "DriverPay (WD)",
    row_grain: "One historical driver assignment/pay record. Team trucks normally produce two rows, one per driver; solo assignments normally produce one row with Solo_Driver_if_1 = 1.",
    primary_key: "ID (Supabase identity; not the Ninox DriverPay record ID)",
    use_for: ["actual assignment history", "departures by Out Date", "returns by Return Date", "driver pay terms", "transfers", "terminations"],
    do_not_use_for: ["planned teams", "weekly truck financial totals", "counting rows as trucks"],
    calculation_rules: [
      "Departure questions filter Out Date only. Return questions filter Return Date only. Do not require both unless the user explicitly asks for assignment overlap.",
      "Count distinct Truck_Number when the user asks for trucks; DriverPay rows count drivers/assignments.",
      "MoneyPerDaysigned is the stored daily rate and currently equals MoneyPerWeekSigned / 7 in verified live rows.",
      "For a matching settlement week, driver pay is MoneyPerWeekSigned + CPM × max(Driven_miles − Pay CPM after Miles, 0). Calculate per driver assignment; do not divide team pay unless explicitly instructed.",
      "For assignment overlap with a settlement period: Out Date <= settlement To and (Return Date is null or Return Date >= settlement From), then review transfers and terminations that occur inside the period.",
    ],
    fields: {
      Truck_Number: field("text", true, "Actual assigned truck number from Ninox WD field IA / TruckNumber_. Use as an identifier, not a quantity."),
      "Out Date": field("date", true, "Actual date the driver and truck left to work. Use alone for departure questions.", { ninox_field: "WD.O" }),
      "Return Date": field("date", true, "Date the driver/truck returned for driver rest and truck yard/off-duty status. Use alone for historical return questions.", { ninox_field: "WD.R" }),
      Transfer: field("text", true, "Transfer direction. Verified live values include Transfer To Other Truck and Transfer From Other Truck.", { ninox_field: "WD.I9" }),
      DriversDB_ID: field("text", true, "Canonical DriversDB record ID stored as text. Join to drivers.Ninox_ID::text."),
      Termination: field("text", true, "Early assignment/contract ending reason. Verified live values include Driver Changed and Fired; the Ninox catalog also defines Early Broke Contract.", { ninox_field: "WD.LA" }),
      "Termination Date": field("date", true, "Date this DriverPay assignment ended for the stated termination reason."),
      "Transfer Date": field("date", true, "Date of the assignment/truck transfer."),
      "Transfer Truck": field("text", true, "Counterparty truck: destination for Transfer To Other Truck and origin for Transfer From Other Truck."),
      Solo_Driver_if_1: field("numeric", true, "1 identifies a solo assignment. Null or another value is not proof of exactly two rows; still deduplicate Truck_Number for truck counts.", { ninox_field: "WD.PC" }),
      MoneyPerWeekSigned: field("numeric", true, "Fixed weekly driver salary for this assignment.", { ninox_field: "WD.H6" }),
      MoneyPerDaysigned: field("numeric", true, "Stored daily driver salary; verified as weekly salary divided by 7 in current rows.", { ninox_field: "WD.G6" }),
      CPM: field("numeric", true, "Per-mile pay rate applied only above the weekly threshold.", { ninox_field: "WD.DA" }),
      "Pay CPM after Miles": field("numeric", true, "Weekly mileage threshold above which CPM pay applies.", { ninox_field: "WD.EA" }),
      "Driver Name": field("text", true, "Driver display-name snapshot for this assignment."),
      "First Name": field("text", true, "Driver first-name snapshot for this assignment."),
      "Last Name": field("text", true, "Driver last-name snapshot for this assignment."),
      "E-mail": field("text", true, "Sensitive driver email snapshot.", { sensitive: true }),
      "Phone Number": field("text", true, "Sensitive driver phone snapshot.", { sensitive: true }),
      CDL: field("text", true, "Sensitive commercial driver-license snapshot.", { sensitive: true }),
      State: field("text", true, "CDL issuing-state snapshot."),
      owner: field("text", true, "Owner/entity associated with this historical assignment, not necessarily the truck's current owner.", { ninox_field: "WD.KB" }),
      Samsara_ID: field("text", true, "Samsara truck/vehicle identifier used by integrations.", { sensitive: true, ninox_field: "WD.FB" }),
      Dispatch_Name_: field("text", true, "Historical dispatch value for this assignment. Live history includes group labels and legacy dispatcher names; filter exact stored values.", { ninox_field: "WD.ZA" }),
      Temporal_Driver: field("text", true, "Temporary-CDL indicator stored as text; verified values are Yes, No, or null.", { ninox_field: "WD.UJ" }),
      ID: field("bigint", false, "Supabase identity primary key for this imported row; not the Ninox DriverPay record ID."),
      organization_id: field("uuid", false, "Tenant organization ID. Applied server-side and returned for traceability."),
    },
  },
  drivers: {
    report: "drivers",
    source: "public.drivers",
    ninox_source: "DriversDB (Z); the local Ninox catalog currently has no field-level Z-table definitions",
    row_grain: "One current driver-master profile. This is current state, not historical assignment or pay history.",
    primary_key: "ID (Supabase identity); Ninox_ID is the unique business/source key",
    use_for: ["current driver identity", "current contact and CDL profile when sensitive access is authorized", "joining DriverPay through Ninox_ID"],
    do_not_use_for: ["historical truck assignment", "historical owner/dispatch attribution", "compliance decisions without source validation"],
    fields: {
      FullName: field("text", true, "Current full driver display name."),
      "First Name": field("text", true, "Current first name."),
      "Middle Name": field("text", true, "Current middle name."),
      "Last Name": field("text", true, "Current last name."),
      "E-mail": field("text", true, "Sensitive current driver email.", { sensitive: true }),
      "Phone Number": field("text", true, "Sensitive current driver phone number.", { sensitive: true }),
      "Years Of Experience": field("numeric", true, "Experience value calculated in Ninox. Use the stored value unless the user explicitly requests recalculation."),
      DOB: field("date", true, "Sensitive date of birth. Validate anomalies before any compliance use.", { sensitive: true }),
      "Company Name (This is NOT the Insurance)": field("text", true, "Driver-associated employer/company; explicitly not the Insurance field."),
      CDL: field("text", true, "Sensitive commercial driver-license number.", { sensitive: true }),
      State: field("text", true, "State that issued the driver's CDL."),
      "CDL Expiration": field("text", true, "Sensitive CDL-expiration value stored as text. Validate its format before date arithmetic.", { sensitive: true }),
      Gender: field("text", true, "Sensitive driver gender value as stored.", { sensitive: true }),
      Insurance: field("text", true, "Driver-associated insurance category/code. Use the literal stored value; code expansion is not established."),
      Ninox_ID: field("numeric", true, "Unique Ninox DriversDB source ID and preferred business join key."),
      ID: field("bigint", false, "Supabase identity primary key for this imported row; not the Ninox driver ID."),
      organization_id: field("uuid", false, "Tenant organization ID. Applied server-side and returned for traceability."),
      "Date of Hire": field("date", true, "Current driver hire date. The physical column and type are verified; its source-field mapping and any employment-policy semantics are not established."),
    },
  },
  returns: {
    report: "returns",
    source: "public.returns",
    ninox_source: "Returns (S)",
    row_grain: "One current returning-driver/truck row. Team trucks normally have two rows; count distinct Truck for truck totals.",
    primary_key: "ID (Supabase identity)",
    use_for: ["current operational expected returns", "return-date lists", "driver contact only when sensitive access is authorized"],
    do_not_use_for: ["historical returns", "departures", "financial calculations"],
    calculation_rules: [
      "Return Date is a nullable PostgreSQL date. Filter it directly with inclusive ISO YYYY-MM-DD boundaries.",
      "Use DriverPay.Return Date for historical returns. returns is a volatile current operational list.",
      "Ninox_ID is the Returns source-record ID, not a driver ID or DriversDB_ID. This representation also has a sensitive CDL field; use CDL only for an exact driver link when it matches a related approved record.",
    ],
    fields: {
      Insurance: field("text", true, "Insurance category/code for the returning assignment/truck. Use the literal value; code expansion is not established."),
      Truck: field("text", true, "Returning truck number. Deduplicate for truck counts.", { ninox_field: "S.A" }),
      "Driver Name": field("text", true, "Driver display name for this return row.", { ninox_field: "S.B" }),
      "Phone Number": field("text", true, "Sensitive driver contact number.", { sensitive: true, ninox_field: "S.E" }),
      "Return Date": field("date", true, "Expected return date to yard/rest; null means no date is currently stored, not a text status.", { ninox_field: "S.H" }),
      ID: field("bigint", false, "Supabase identity primary key for this imported row."),
      Ninox_ID: field("numeric", true, "Ninox Returns source-record ID. Do not join to drivers.Ninox_ID."),
      organization_id: field("uuid", false, "Tenant organization ID. Applied server-side and returned for traceability."),
      CDL: field("text", true, "Sensitive commercial driver-license value for this return row. The physical column is verified; use it for an exact driver link only when a related approved record has the same verified CDL.", { sensitive: true }),
    },
    source_omissions: ["Ninox S.E3 Solo", "Ninox S.J3 DriverDB_Id_saved", "Ninox S.K3 Driver_id_Pay_ are not columns in this Supabase table"],
  },
  settlements: {
    report: "settlements",
    source: "public.settlements",
    ninox_source: "Facturacion (DE)",
    row_grain: "One truck identifier or owner-allocation bucket for one Tuesday-through-Monday settlement period. (Truck, From, To) is unique in verified live data.",
    primary_key: "ID (Supabase identity)",
    use_for: ["weekly gross", "expenses", "net", "mileage", "driver-pay expense", "period-specific owner and dispatch attribution"],
    do_not_use_for: ["current truck ownership", "current driver assignment", "adding components to already-complete totals"],
    period_rules: [
      "From is Tuesday and To is the following Monday. Both facts were verified across current live rows.",
      "period_from and period_to are inclusive bounds on the From field. Use an exact Tuesday as both values for one settlement week.",
      "Do not infer current cycle from To Report alone. Historical rows contain Yes while the newest observed cycle contains true; use an explicit period.",
      "A period is not financially complete merely because rows exist. Check requested financial fields for nulls before calling it complete.",
    ],
    owner_bucket_rules: [
      "Truck 1 is Carlos's owner-assignment bucket, Truck 2 is Jorge's, and Truck 3 is CDT's. They are not physical trucks.",
      "Include bucket rows in the respective owner's general settlement totals because truck_loans and Insurance from real trucks that lack dedicated rows can be aggregated there.",
      "Exclude Truck 1, 2, and 3 from physical-truck counts, physical-truck rankings, and fleet joins unless the user explicitly asks for allocation buckets.",
    ],
    calculation_rules: [
      "Use stored Gross as total gross. The physical field tonu is an additional income component already included in Gross; the Ninox source catalog maps the related source concept to Facturado Compass. Do not interpret it as freight tonnage or add it again.",
      "Use stored Total Expenses for total-expense questions. It already includes component expenses and Total Driver Pay; do not add components again.",
      "Use stored Net as authoritative. Gross_with_%_deduction_All − Total Expenses is the intended formula but verified live data contains rare exceptions and rows with null expense totals.",
      "Gross_with_%_deduction_All = Gross × (%AppliedSaved / 100) for eligible verified rows.",
      "Attribute historical totals using settlements.Owner and settlements.Dispatch, never current trucks.owner or trucks.dispatcher.",
    ],
    fields: {
      Truck: field("text", true, "Truck number or synthetic owner bucket (1=Carlos, 2=Jorge, 3=CDT).", { ninox_field: "DE.K" }),
      truck_insurance: field("text", true, "Truck insurance category/code for this settlement period."),
      Dispatch: field("text", true, "Historical dispatch value for this settlement period. Use exact stored values; history includes group labels and legacy dispatcher names.", { ninox_field: "DE.X3" }),
      Owner: field("text", true, "Historical owner/entity for this settlement period."),
      Gross: field("numeric", true, "Stored total gross income before company percentage and expenses. Do not add tonu again.", { ninox_field: "DE.L4" }),
      tonu: field("numeric", true, "Physical field name retained from import. Additional/Compass income component already included in Gross; do not treat as a tonnage quantity or add again.", { ninox_related_field: "DE.M1 / Facturado Compass" }),
      "Total Expenses": field("numeric", true, "Stored complete settlement-expense total. Do not add component columns again.", { ninox_field: "DE.Z4" }),
      Net: field("numeric", true, "Stored settlement net and authoritative net value. The intended subtraction formula has rare live exceptions.", { ninox_field: "DE.A5" }),
      From: field("date", true, "Settlement period start date; Tuesday.", { ninox_field: "DE.L" }),
      To: field("date", true, "Settlement period end date; Monday, six days after From."),
      truck_loans: field("numeric", true, "Truck loan/dealer payment expense. Some real-truck amounts are represented in owner bucket rows 1/2/3.", { ninox_field: "DE.Q3" }),
      Otro: field("numeric", true, "Expense without a more specific category."),
      "LTR Invoices": field("numeric", true, "Lightning Trucks Repairs internal shop/mechanics invoice expense."),
      Tolls: field("numeric", true, "Toll expense component."),
      BestPass: field("numeric", true, "BestPass expense component."),
      Insurance: field("numeric", true, "Insurance expense component. Some real-truck amounts are represented in owner bucket rows 1/2/3."),
      CabCards: field("numeric", true, "Cab-card expense component."),
      "Trailer Rentals": field("numeric", true, "Trailer-rental expense component."),
      samsara: field("numeric", true, "Samsara expense component."),
      PrePass: field("numeric", true, "PrePass expense component."),
      "Total Driver Pay": field("numeric", true, "Stored total driver-pay expense for this truck and settlement period.", { ninox_field: "DE.L3" }),
      "Fuel Expenses": field("numeric", true, "Fuel expense component for this truck and settlement period."),
      "To Report": field("text", true, "Imported reporting flag with mixed historical storage. Do not use alone to infer the current cycle; require an explicit period."),
      "%AppliedSaved": field("numeric", true, "Company percentage applied to Gross.", { ninox_field: "DE.T2" }),
      "Gross_with_%_deduction_All": field("numeric", true, "Gross after applying %AppliedSaved.", { ninox_field: "DE.G8" }),
      Driven_miles: field("numeric", true, "Miles driven during the settlement period.", { ninox_field: "DE.S5" }),
      ID: field("bigint", false, "Supabase identity primary key for this imported row."),
      organization_id: field("uuid", false, "Tenant organization ID. Applied server-side and returned for traceability."),
    },
  },
  trucks: {
    report: "trucks",
    source: "public.trucks",
    ninox_source: "TrucksDB (E)",
    row_grain: "One current truck-master or synthetic owner-bucket row per unique truck_number. ID is the primary key; truck_number has a unique constraint.",
    primary_key: "ID; truck_number is the unique business key",
    use_for: ["current fleet identity", "current owner and dispatcher", "current vehicle/operational metadata"],
    do_not_use_for: ["historical owner/dispatch attribution", "historical financial totals", "treating allocation buckets 1/2/3 as physical trucks"],
    rules: [
      "truck_number 1, 2, and 3 are owner-assignment buckets (Carlos, Jorge, CDT), not physical trucks. Exclude them from physical-fleet counts.",
      "dispatcher and owner are current values. Use DriverPay or settlements fields for historical attribution.",
      "Out Of Services is a current dispatcher value, but it is not equivalent to the exact Ninox in-yard/off-duty formula, which uses unavailable days_in_yard_ and insurance-choice fields.",
      "Use literal stored mechanic_status values. Current values include Work in Progress, Heavy Work No ETA, Ready for Q.C., and Ready To Go; blank/null means no status is stored.",
    ],
    fields: {
      truck_number: field("numeric", false, "Unique current truck number or synthetic owner bucket. Use as the business lookup key.", { ninox_field: "E.A" }),
      dispatcher: field("text", true, "Current dispatcher/group. Verified current values include Group 1, Group 2, CDT, Solo, and Out Of Services.", { ninox_field: "E.YF" }),
      insurance: field("text", true, "Current truck insurance provider/category. Verified current values include CTC, CDT, LTL, and Need Ins.; value sets can change.", { ninox_field: "E.Y4" }),
      vin: field("text", true, "Sensitive unique vehicle identification number.", { sensitive: true, ninox_field: "E.CG" }),
      make: field("text", true, "Vehicle make/model display value.", { ninox_field: "E.DG" }),
      odometer_miles: field("numeric", true, "Current recorded odometer value in miles.", { ninox_field: "E.OF" }),
      owner: field("text", true, "Current owner/entity. Use exact stored values; current data includes company, O/O, and named-owner values.", { ninox_field: "E.VF" }),
      last_known_address: field("text", true, "Sensitive most recently known Samsara-derived address/location.", { sensitive: true, ninox_field: "E.PF" }),
      model_year: field("numeric", true, "Vehicle model year.", { ninox_field: "E.IJ" }),
      license_plate: field("text", true, "Sensitive vehicle license-plate value.", { sensitive: true, ninox_field: "E.HJ" }),
      yard_location: field("text", true, "Current selected/derived location such as 301 Yard or a service vendor.", { ninox_field: "E.X1" }),
      samsara_last_connected_at: field("timestamptz", true, "Timestamp when Samsara most recently connected/reported.", { ninox_field: "E.SF" }),
      samsara_vehicle_id: field("text", true, "Sensitive Samsara vehicle identifier.", { sensitive: true, ninox_field: "E.BM" }),
      mechanic_status: field("text", true, "Current mechanic/shop status. Use the literal stored value; blank/null means no status is stored.", { ninox_field: "E.TA" }),
      ID: field("bigint", false, "Supabase identity primary key for this row; not the Ninox TrucksDB record ID."),
      organization_id: field("uuid", false, "Tenant organization ID. Applied server-side and returned for traceability."),
      Ninox_ID: field("numeric", true, "Ninox TrucksDB source record ID. The physical column and type are verified; it is not the canonical truck number and its broader business semantics are not established."),
    },
  },
} as const;

export const REPORTS = {
  settlement_summary: {
    source: "reporting.settlement_summary",
    row_grain: TABLES.settlements.row_grain,
    returned_fields: ["settlement_id", "organization_id", "truck", "owner", "period_from", "period_to", "gross", "total_expenses", "net", "total_driver_pay", "fuel_expenses", "driven_miles"],
    filters: {
      truck: "exact text truck/bucket identifier",
      owner: "exact historical owner",
      period_from: "inclusive lower bound on period_from, YYYY-MM-DD",
      period_to: "inclusive upper bound on period_from, YYYY-MM-DD",
    },
    required_anchor: "Explicit report requests require truck or period_from. Omitted-report legacy requests preserve the original unanchored behavior.",
    sort: ["period_from asc", "settlement_id asc"],
  },
  settlements: {
    ...TABLES.settlements,
    filters: {
      truck: "exact Truck",
      owner: "exact historical Owner",
      dispatch: "exact historical Dispatch",
      insurance: "exact truck_insurance",
      to_report: "exact stored To Report value; never use alone to infer current cycle",
      period_from: "inclusive lower bound on From, YYYY-MM-DD",
      period_to: "inclusive upper bound on From, YYYY-MM-DD",
    },
    required_anchor: "truck or period_from",
    sort: ["From asc", "ID asc"],
  },
  driver_pay: {
    ...TABLES.driver_pay,
    filters: {
      truck_number: "exact Truck_Number",
      driver_id: "exact DriversDB_ID",
      out_from: "inclusive lower Out Date, YYYY-MM-DD",
      out_to: "inclusive upper Out Date, YYYY-MM-DD",
      return_from: "inclusive lower Return Date, YYYY-MM-DD",
      return_to: "inclusive upper Return Date, YYYY-MM-DD",
      transfer: "exact Transfer",
      termination: "exact Termination",
      solo: "true means Solo_Driver_if_1 = 1; false includes null and values other than 1",
      owner: "exact historical owner",
      dispatch: "exact historical Dispatch_Name_",
      temporal_driver: "exact stored Yes/No value",
    },
    required_anchor: "truck_number, driver_id, out_from, or return_from",
    sort: ["Out Date asc nulls last", "ID asc"],
  },
  drivers: {
    ...TABLES.drivers,
    filters: {
      driver_id: "exact Ninox_ID",
      name: "case-insensitive partial FullName discovery search",
      first_name: "exact First Name",
      last_name: "exact Last Name",
      state: "exact CDL issuing State",
      insurance: "exact driver Insurance value",
      company: "exact employer/company, not insurance",
      min_experience: "inclusive numeric Years Of Experience lower bound",
      max_experience: "inclusive numeric Years Of Experience upper bound",
      hire_from: "inclusive Date of Hire lower bound, YYYY-MM-DD",
      hire_to: "inclusive Date of Hire upper bound, YYYY-MM-DD",
    },
    sort: ["Ninox_ID asc nulls last", "ID asc"],
  },
  returns: {
    ...TABLES.returns,
    filters: {
      truck: "exact Truck",
      insurance: "exact Insurance",
      ninox_id: "exact Returns source-record Ninox_ID",
      driver_name: "case-insensitive partial Driver Name discovery search",
      return_from: "inclusive Return Date lower bound, YYYY-MM-DD",
      return_to: "inclusive Return Date upper bound, YYYY-MM-DD",
    },
    sort: ["Return Date asc nulls last", "ID asc"],
  },
  trucks: {
    ...TABLES.trucks,
    filters: {
      truck_number: "exact numeric truck/bucket number",
      ninox_id: "exact numeric TrucksDB source-record Ninox_ID",
      dispatcher: "exact current dispatcher",
      owner: "exact current owner",
      insurance: "exact current insurance",
      yard_location: "exact current location",
      mechanic_status: "exact current mechanic status",
      make: "case-insensitive partial make/model search",
      min_odometer: "inclusive numeric lower bound",
      max_odometer: "inclusive numeric upper bound",
      min_model_year: "inclusive numeric lower bound",
      max_model_year: "inclusive numeric upper bound",
      physical_only: "true excludes synthetic owner buckets 1, 2, and 3; false includes all rows",
    },
    sort: ["truck_number asc", "ID asc"],
  },
} as const;
